all:
  hosts:
    master:
      ansible_host: 158.160.37.204
      ip: 10.0.1.29
      access_ip: 158.160.37.204
    worker-1:
      ansible_host: 89.169.174.181
      ip: 10.0.2.7
      access_ip: 89.169.174.181
    worker-2:
      ansible_host: 89.169.166.177
      ip: 10.0.2.35
      access_ip: 89.169.166.177
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
