- hosts: all
  tasks:
    - name: Add SSH public key to authorized_keys
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_ed25519.pub') }}"
